#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Ghostty
rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty
#
# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/nvim/phpactor $HOME/.config/phpactor

# Telescope fzf error fix
#cd ~/.local/share/nvim/lazy/telescope-fzf-native.nvim && make && cd -
